# Generated by Django 5.0.2 on 2024-11-03 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate')], default='Undergraduate', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('globalsearch_key', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_searcher.coursecareer')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_searcher.school')),
            ],
            options={
                'unique_together': {('level', 'school')},
            },
        ),
        migrations.AddField(
            model_name='coursecareer',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='careers', to='course_searcher.school'),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('globalsearch_key', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='course_searcher.school')),
            ],
            options={
                'unique_together': {('name', 'year', 'school')},
            },
        ),
        migrations.CreateModel(
            name='CourseClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(max_length=20)),
                ('room', models.CharField(max_length=50)),
                ('days_and_times', models.CharField(max_length=100)),
                ('meeting_dates', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('waitlisted', 'Waitlisted')], default='open', max_length=20)),
                ('instruction_mode', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course_searcher.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course_searcher.instructor')),
            ],
            options={
                'verbose_name_plural': 'Course Classes',
                'ordering': ['course', 'section'],
                'unique_together': {('course', 'section')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='coursecareer',
            unique_together={('name', 'school')},
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(max_length=100)),
                ('globalsearch_key', models.TextField(max_length=100)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course_searcher.coursecareer')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course_searcher.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='course_searcher.term')),
            ],
            options={
                'unique_together': {('name', 'school', 'term', 'career')},
            },
        ),
    ]
