# Generated by Django 5.0.2 on 2024-11-03 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseclass',
            options={'ordering': ('course', 'section'), 'verbose_name_plural': 'Course Classes'},
        ),
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='course_searcher.term'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together={('course', 'section', 'term')},
        ),
    ]
