# Generated by Django 5.0.2 on 2024-11-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0002_alter_courseclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='term_id',
            field=models.BigIntegerField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
