# Generated by Django 5.0.2 on 2024-11-05 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0003_term_term_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='term_id',
            new_name='external_id',
        ),
    ]
