# Generated by Django 5.0.2 on 2024-11-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0004_rename_term_id_term_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='external_id',
        ),
    ]
