# Generated by Django 5.0.2 on 2024-11-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0005_remove_term_external_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('name', 'year')},
        ),
        migrations.AddField(
            model_name='term',
            name='schools',
            field=models.ManyToManyField(related_name='terms', to='course_searcher.school'),
        ),
        migrations.RemoveField(
            model_name='term',
            name='school',
        ),
    ]
