# Generated by Django 5.0.2 on 2024-11-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0006_alter_term_unique_together_term_schools_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='globalsearch_key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
