# Generated by Django 5.0.2 on 2024-11-05 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0007_alter_school_globalsearch_key'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursecareer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='coursecareer',
            name='name',
            field=models.CharField(choices=[('Graduate', 'Graduate'), ('Undergraduate', 'Undergraduate')], default='Undergraduate', max_length=20, unique=True),
        ),
    ]
