# Generated by Django 5.0.2 on 2024-11-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0008_alter_coursecareer_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecareer',
            name='school',
        ),
        migrations.AddField(
            model_name='coursecareer',
            name='schools',
            field=models.ManyToManyField(related_name='careers', to='course_searcher.school'),
        ),
    ]
