# Generated by Django 5.0.2 on 2024-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0009_remove_coursecareer_school_coursecareer_schools'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
