# Generated by Django 5.0.2 on 2024-11-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0010_term_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='terms',
            field=models.ManyToManyField(related_name='courses', to='course_searcher.term'),
        ),
    ]
