# Generated by Django 5.0.2 on 2024-11-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0011_course_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecareer',
            name='name',
            field=models.CharField(choices=[('GRAD', 'Graduate'), ('UGRD', 'Undergraduate')], default='UGRD', max_length=20, unique=True),
        ),
    ]
