# Generated by Django 5.0.2 on 2024-11-10 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0012_alter_coursecareer_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'school', 'term')},
        ),
        migrations.RemoveField(
            model_name='subject',
            name='career',
        ),
    ]
