# Generated by Django 5.0.2 on 2024-11-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0013_alter_subject_unique_together_remove_subject_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecareer',
            name='globalsearch_key',
            field=models.CharField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursecareer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
