# Generated by Django 5.0.2 on 2024-11-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0014_coursecareer_globalsearch_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
