# Generated by Django 5.0.2 on 2024-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0015_school_is_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
