# Generated by Django 5.0.2 on 2024-11-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0016_subject_is_preferred'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'school')},
        ),
        migrations.AddField(
            model_name='subject',
            name='terms',
            field=models.ManyToManyField(related_name='subjects', to='course_searcher.term'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='term',
        ),
    ]
