# Generated by Django 5.0.2 on 2024-11-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0017_alter_subject_unique_together_subject_terms_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='subject',
            name='schools',
            field=models.ManyToManyField(related_name='subjects', to='course_searcher.school'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='globalsearch_key',
            field=models.TextField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='school',
        ),
    ]
