# Generated by Django 5.0.2 on 2024-11-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0018_alter_subject_unique_together_subject_schools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecareer',
            name='terms',
            field=models.ManyToManyField(related_name='careers', to='course_searcher.term'),
        ),
    ]
