# Generated by Django 5.0.2 on 2025-01-22 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0019_coursecareer_terms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseclass',
            name='days_and_times',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='meeting_dates',
        ),
        migrations.RemoveField(
            model_name='courseclass',
            name='room',
        ),
        migrations.AlterField(
            model_name='term',
            name='globalsearch_key',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='InstructionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('days_and_times', models.CharField(max_length=100)),
                ('meeting_dates', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=50)),
                ('course_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_entries', to='course_searcher.courseclass')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_entries', to='course_searcher.instructor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
