# Generated by Django 5.0.2 on 2025-01-24 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0020_remove_courseclass_days_and_times_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='course_searcher.subject'),
            preserve_default=False,
        ),
    ]
