# Generated by Django 5.0.2 on 2025-01-25 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0021_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructionentry',
            name='term',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instruction_entries', to='course_searcher.term'),
            preserve_default=False,
        ),
    ]
