# Generated by Django 5.0.2 on 2025-01-26 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0022_instructionentry_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
