# Generated by Django 5.0.2 on 2025-01-26 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0023_courseclass_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
