# Generated by Django 5.0.2 on 2025-01-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0024_alter_subject_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecareer',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='term',
            name='is_preferred',
            field=models.BooleanField(default=False),
        ),
    ]
