# Generated by Django 5.0.2 on 2025-02-02 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0025_coursecareer_is_preferred_term_is_preferred'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='designation',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
