# Generated by Django 5.0.2 on 2025-02-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0026_course_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='short_name',
        ),
        migrations.AddField(
            model_name='course',
            name='subject_abbreviation',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
