# Generated by Django 5.0.2 on 2025-02-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0027_remove_subject_short_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject_abbreviation',
            field=models.CharField(default='', max_length=100),
        ),
    ]
