# Generated by Django 5.0.2 on 2025-02-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0028_alter_course_subject_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseclass',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courseclass',
            name='url',
            field=models.CharField(max_length=1000),
        ),
    ]
