# Generated by Django 5.0.2 on 2025-02-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0029_courseclass_title_alter_courseclass_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseclass',
            old_name='title',
            new_name='topic',
        ),
    ]
