# Generated by Django 5.0.2 on 2025-02-03 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0030_rename_title_courseclass_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='designation',
        ),
    ]
