# Generated by Django 5.0.2 on 2025-02-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0031_remove_course_designation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='courseclass',
            name='gs_unique_id',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
