# Generated by Django 5.0.2 on 2025-02-11 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0032_alter_courseclass_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='instructor',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='school',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='course_searcher.school', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructor',
            name='terms',
            field=models.ManyToManyField(related_name='instructors', to='course_searcher.term'),
        ),
        migrations.AlterUniqueTogether(
            name='instructionentry',
            unique_together={('term', 'course_class', 'days_and_times', 'meeting_dates', 'room')},
        ),
    ]
