# Generated by Django 5.0.2 on 2025-02-12 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0033_remove_instructor_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='full_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='instructor',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='course_searcher.school'),
        ),
    ]
