# Generated by Django 5.0.2 on 2025-02-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0034_rename_full_name_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructor',
            unique_together={('name', 'school')},
        ),
    ]
