# Generated by Django 5.0.2 on 2025-02-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0035_alter_instructor_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='subject_abbreviation',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='Course Code'),
        ),
    ]
