# Generated by Django 5.0.2 on 2025-02-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0036_remove_course_subject_abbreviation_course_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'level', 'school')},
        ),
    ]
