# Generated by Django 5.0.2 on 2025-02-13 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0037_alter_course_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseClass',
            new_name='CourseSection',
        ),
        migrations.RenameField(
            model_name='instructionentry',
            old_name='course_class',
            new_name='course_section',
        ),
        migrations.AlterUniqueTogether(
            name='instructionentry',
            unique_together={('term', 'course_section', 'days_and_times', 'meeting_dates', 'room')},
        ),
    ]
