# Generated by Django 5.0.2 on 2025-02-13 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0038_rename_courseclass_coursesection_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesection',
            options={'ordering': ('course', 'section'), 'verbose_name_plural': 'Course Sections'},
        ),
    ]
