# Generated by Django 5.0.2 on 2025-02-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0039_alter_coursesection_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='designation',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='', max_length=10),
        ),
    ]
