# Generated by Django 5.0.2 on 2025-02-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0040_course_designation_alter_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mo', 'Monday'), ('Tu', 'Tuesday'), ('We', 'Wednesday'), ('Th', 'Thursday'), ('Fr', 'Friday'), ('Sa', 'Saturday'), ('Su', 'Sunday')], max_length=10, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='instructionentry',
            unique_together={('term', 'course_section', 'start_time', 'end_time', 'start_date', 'end_date', 'building', 'room_number')},
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='building',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='end_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='end_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='floor_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='room_number',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='start_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='start_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instructionentry',
            name='days',
            field=models.ManyToManyField(related_name='instruction_entries', to='course_searcher.day'),
        ),
        migrations.RemoveField(
            model_name='instructionentry',
            name='days_and_times',
        ),
        migrations.RemoveField(
            model_name='instructionentry',
            name='meeting_dates',
        ),
        migrations.RemoveField(
            model_name='instructionentry',
            name='room',
        ),
    ]
