# Generated by Django 5.0.2 on 2025-02-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0043_alter_instructionentry_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
