# Generated by Django 5.0.2 on 2025-02-22 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0046_rename_room_number_instructionentry_room_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together={('term', 'number')},
        ),
    ]
