# Generated by Django 5.0.2 on 2025-02-24 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_searcher', '0047_alter_coursesection_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instructionentry',
            unique_together={('term', 'course_section', 'start_time', 'end_time', 'start_date', 'end_date', 'building', 'room', 'instructor')},
        ),
    ]
