services:
  class_tracker_db_init:
    image: mm-class-tracker-image
    container_name: mm-class-tracker-db-init
    build:
      context: .
      args:
        ENV_TYPE: dev
        UID: "${UID}"
    command: bash -c "uv run python manage.py migrate"
    # command: >
    #   bash -c "
    #   trap 'echo SIGTERM received, shutting down...; exit' SIGTERM;
    #   while true; do
    #     sleep 1;
    #   done
    #   "
    tty: true
    user: "${UID}"
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - python_venv_class_tracker:/app/.venv
      - ./:/app
    env_file:
      - .env.dev
    networks:
      - class_tracker_dev

volumes:
  python_venv_class_tracker:
    external: true

networks:
  class_tracker_dev:
    external: true
