services:
  class_tracker_db_init:
    image: mm-class-tracker-image
    container_name: mm-class-tracker-db-init
    build:
      context: .
      args:
        ENV_TYPE: ${ENV_TYPE}
        UID: "${UID}"
    command: bash -c "uv run python manage.py migrate"
    tty: true
    user: "${UID}"
    ports:
      - ${DJANGO_PORT}:${DJANGO_PORT}
    volumes:
      - class_tracker_python_venv:/app/.venv
      - ./:/app
    env_file:
      - ${ENV_FILE}
    networks:
      - class_tracker_dev

volumes:
  class_tracker_python_venv:
    external: true

networks:
  class_tracker_dev:
    external: true
