# Generated by Django 5.0.2 on 2025-02-19 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0001_squashed_0041_day_alter_instructionentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='class_tracker.subject'),
        ),
        migrations.AlterField(
            model_name='coursecareer',
            name='globalsearch_key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='gs_unique_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='class_tracker.term'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='building',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='floor_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='room_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instruction_entries', to='class_tracker.term'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
