# Generated by Django 5.0.2 on 2025-02-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0042_alter_course_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructionentry',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='instructionentry',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
