# Generated by Django 5.0.2 on 2025-02-21 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0044_coursesection_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='class_tracker.course'),
        ),
        migrations.AlterField(
            model_name='coursesection',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='class_tracker.term'),
        ),
    ]
