# Generated by Django 5.0.2 on 2025-02-21 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0045_alter_coursesection_course_alter_coursesection_term'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructionentry',
            old_name='room_number',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='instructionentry',
            unique_together={('term', 'course_section', 'start_time', 'end_time', 'start_date', 'end_date', 'building', 'room')},
        ),
    ]
