# Generated by Django 5.0.2 on 2025-02-27 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0049_contact_phonenumber_classalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_contact_by_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='watched_sections',
            field=models.ManyToManyField(related_name='contacts_watching', to='class_tracker.coursesection'),
        ),
    ]
