# Generated by Django 5.0.2 on 2025-02-27 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0050_contact_is_contact_by_phone_contact_watched_sections'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneNumber',
            new_name='ContactInfo',
        ),
    ]
