# Generated by Django 5.0.2 on 2025-02-27 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0051_rename_phonenumber_contactinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_contact_by_phone', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='contact',
            name='watched_sections',
        ),
        migrations.RemoveIndex(
            model_name='classalert',
            name='class_track_contact_59cf56_idx',
        ),
        migrations.AddField(
            model_name='recipient',
            name='watched_sections',
            field=models.ManyToManyField(related_name='watched_by', to='class_tracker.coursesection'),
        ),
        migrations.AlterUniqueTogether(
            name='classalert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classalert',
            name='recipient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='class_tracker.recipient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='class_tracker.recipient'),
        ),
        migrations.AlterUniqueTogether(
            name='classalert',
            unique_together={('recipient', 'course_section', 'datetime_created')},
        ),
        migrations.AddIndex(
            model_name='classalert',
            index=models.Index(fields=['recipient', 'course_section'], name='class_track_recipie_c486af_idx'),
        ),
        migrations.RemoveField(
            model_name='classalert',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
