# Generated by Django 5.0.2 on 2025-08-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0052_recipient_remove_contact_watched_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipient',
            name='watched_sections',
            field=models.ManyToManyField(blank=True, related_name='watched_by', to='class_tracker.coursesection'),
        ),
    ]
