# Generated by Django 5.0.2 on 2025-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0053_alter_recipient_watched_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('hours_renotify_grace_period', models.FloatField(default=6.0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
