# Generated by Django 5.0.2 on 2026-09-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0054_globalsettings'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursesection',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['term', 'number'], name='coursesection_term_number_idx'),
        ),
    ]
