# Generated by Django 5.0.2 on 2025-08-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='access_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
