# Generated by Django 5.0.2 on 2025-08-20 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0054_globalsettings'),
        ('discord_tracker', '0002_discorduser_access_token_discorduser_refresh_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discorduser',
            old_name='verified',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='discorduser',
            name='is_trusted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discorduser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_tracker.school'),
        ),
    ]
