# Generated by Django 5.0.2 on 2025-08-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0004_remove_discorduser_is_trusted_discorduser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discorduser',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
