# Generated by Django 5.0.2 on 2025-08-23 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0005_discorduser_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('trusted', 'Trusted User'), ('manager', 'Discord Manager')], default='regular', max_length=20),
        ),
        migrations.AlterField(
            model_name='uservouch',
            name='voucher',
            field=models.ForeignKey(limit_choices_to={'role__in': ['trusted', 'manager']}, on_delete=django.db.models.deletion.CASCADE, related_name='vouches_given', to='discord_tracker.discorduser'),
        ),
    ]
