# Generated by Django 5.0.2 on 2025-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0006_alter_discorduser_role_alter_uservouch_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('trusted', 'Verified User'), ('manager', 'Discord Manager')], default='regular', max_length=20),
        ),
    ]
