# Generated by Django 5.0.2 on 2025-08-26 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0007_alter_discorduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='datetime_last_synced',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
