# Generated by Django 5.0.2 on 2025-08-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0008_alter_discordserver_datetime_last_synced'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordinvite',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
