# Generated by Django 5.0.2 on 2025-08-26 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0009_discordinvite_is_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordinvite',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='discordinvite',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_invites', to='discord_tracker.discorduser'),
        ),
    ]
