# Generated by Django 5.0.2 on 2025-08-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0010_remove_discordinvite_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordinvite',
            name='datetime_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
