# Generated by Django 5.0.2 on 2025-08-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0011_discordinvite_datetime_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='is_required_for_trust',
            field=models.BooleanField(default=False),
        ),
    ]
