# Generated by Django 5.0.2 on 2025-08-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0054_globalsettings'),
        ('discord_tracker', '0012_discordserver_is_required_for_trust'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['server_id', 'is_required_for_trust'], name='discord_tra_server__517987_idx'),
        ),
    ]
