# Generated by Django 5.0.2 on 2025-08-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0013_discordserver_discord_tra_server__517987_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('trusted', 'Trusted User'), ('manager', 'Discord Manager')], default='regular', max_length=20),
        ),
    ]
