# Generated by Django 5.0.2 on 2025-08-29 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0014_alter_discorduser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordinvite',
            name='datetime_approved',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='discordinvite',
            name='datetime_rejected',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='discordinvite',
            name='uses_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='access_token',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='login_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='refresh_token',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='discorduser',
            name='token_expires_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
