# Generated by Django 5.0.2 on 2025-08-30 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0015_alter_discordinvite_datetime_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('num_uses', models.PositiveIntegerField(default=0, editable=False)),
                ('datetime_expires', models.DateTimeField(blank=True, null=True)),
                ('datetime_redeemed', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers_created', to='discord_tracker.discorduser')),
            ],
        ),
        migrations.CreateModel(
            name='UserVoucherRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('datetime_redeemed', models.DateTimeField(auto_now_add=True)),
                ('redeemed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_redemptions', to='discord_tracker.discorduser')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='discord_tracker.uservoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='uservoucher',
            index=models.Index(fields=['created_by'], name='discord_tra_created_7aaa24_idx'),
        ),
    ]
