# Generated by Django 5.0.2 on 2025-08-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0016_uservoucher_uservoucherredemption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserVoucher',
            new_name='UserReferral',
        ),
        migrations.RenameModel(
            old_name='UserVoucherRedemption',
            new_name='UserReferralRedemption',
        ),
        migrations.RenameIndex(
            model_name='userreferral',
            new_name='discord_tra_created_25273e_idx',
            old_name='discord_tra_created_7aaa24_idx',
        ),
    ]
