# Generated by Django 5.0.2 on 2025-08-30 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0017_rename_uservoucher_userreferral_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreferralredemption',
            old_name='voucher',
            new_name='referral',
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_created', to='discord_tracker.discorduser'),
        ),
        migrations.AlterField(
            model_name='userreferralredemption',
            name='redeemed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_redemptions', to='discord_tracker.discorduser'),
        ),
    ]
