# Generated by Django 5.0.2 on 2025-08-30 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0018_rename_voucher_userreferralredemption_referral_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreferral',
            name='datetime_redeemed',
        ),
    ]
