# Generated by Django 5.0.2 on 2025-08-30 03:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0020_userreferral_expiry_timeframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
