# Generated by Django 5.0.2 on 2025-08-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0021_alter_userreferral_max_uses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='expiry_timeframe',
            field=models.CharField(choices=[('1w', '1 Week'), ('2w', '2 Weeks'), ('permanent', 'Never Expires')], default='1w', help_text='Expiry timeframe from creation date', max_length=20),
        ),
    ]
