# Generated by Django 5.0.2 on 2025-08-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0022_alter_userreferral_expiry_timeframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreferral',
            name='max_uses_choices',
            field=models.CharField(choices=[('10', '10 Uses'), ('20', '20 Uses'), ('50', '50 Uses'), ('100', '100 Uses')], default='10', help_text='Preset options for maximum uses', max_length=10),
        ),
    ]
