# Generated by Django 5.0.2 on 2025-08-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0023_userreferral_max_uses_choices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreferral',
            old_name='max_uses_choices',
            new_name='max_uses_choice',
        ),
    ]
