# Generated by Django 5.0.2 on 2025-08-30 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0024_rename_max_uses_choices_userreferral_max_uses_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uservouch',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='uservouch',
            name='vouched_for',
        ),
        migrations.RemoveField(
            model_name='uservouch',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='RequiredDiscordServer',
        ),
        migrations.DeleteModel(
            name='UserVouch',
        ),
    ]
