# Generated by Django 5.0.2 on 2025-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0025_alter_uservouch_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discorduser',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('manager', 'Discord Manager')], default='regular', max_length=20),
        ),
    ]
