# Generated by Django 5.0.2 on 2025-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0027_alter_discordserver_privacy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='max_uses_choice',
            field=models.CharField(choices=[('20', '20 Uses'), ('50', '50 Uses'), ('100', '100 Uses')], default='20', help_text='Preset options for maximum uses', max_length=10),
        ),
    ]
