# Generated by Django 5.0.2 on 2025-08-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0028_alter_userreferral_max_uses_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
