# Generated by Django 5.0.2 on 2025-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0029_discordserver_member_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public - visible to all users'), ('private', 'Private - Authenticated users only')], default='public', max_length=20),
        ),
    ]
