# Generated by Django 5.0.2 on 2025-08-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0030_alter_discordserver_privacy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordserver',
            name='privacy_level',
            field=models.CharField(choices=[('public', 'Public Server'), ('private', 'Private Server')], default='public', max_length=20),
        ),
    ]
