# Generated by Django 5.0.2 on 2025-09-01 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0031_alter_discordserver_privacy_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordinvite',
            name='notes_md',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
