# Generated by Django 5.0.2 on 2025-09-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_tracker', '0054_globalsettings'),
        ('discord_tracker', '0032_alter_discordinvite_notes_md'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discordserver',
            name='discord_tra_server__517987_idx',
        ),
        migrations.RenameField(
            model_name='discordserver',
            old_name='is_required_for_trust',
            new_name='is_featured',
        ),
        migrations.AddIndex(
            model_name='discordserver',
            index=models.Index(fields=['server_id', 'is_featured'], name='discord_tra_server__f3cb17_idx'),
        ),
    ]
