# Generated by Django 5.0.2 on 2025-09-25 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0033_remove_discordserver_discord_tra_server__517987_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreferral',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='userreferral',
            name='max_uses_choice',
            field=models.CharField(choices=[('20', '20 Uses'), ('50', '50 Uses'), ('100', '100 Uses'), ('0', 'Unlimited Uses')], default='20', help_text='Preset options for maximum uses', max_length=10),
        ),
    ]
