# Generated by Django 5.0.2 on 2025-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0034_alter_userreferral_max_uses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='datetime_established',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
