# Generated by Django 5.0.2 on 2026-01-09 01:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0035_discordserver_datetime_established'),
    ]

    operations = [
        migrations.AddField(
            model_name='discordserver',
            name='last_checked',
            field=models.DateField(blank=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
