# Generated by Django 5.0.2 on 2026-01-09 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0036_discordserver_last_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
            options={
                'ordering': ['-datetime_created'],
                'indexes': [models.Index(fields=['-datetime_created'], name='discord_tra_datetim_6c4316_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
                ('datetime_read', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='discord_tracker.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_alerts', to='discord_tracker.discorduser')),
            ],
            options={
                'ordering': ['-datetime_created'],
                'indexes': [models.Index(fields=['user', '-datetime_created'], name='discord_tra_user_id_7a503f_idx'), models.Index(fields=['user', 'is_read'], name='discord_tra_user_id_53c70f_idx'), models.Index(fields=['alert', 'is_read'], name='discord_tra_alert_i_4894e2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='alertrecipient',
            constraint=models.UniqueConstraint(fields=('alert', 'user'), name='unique_alert_recipient'),
        ),
    ]
