# Generated by Django 5.0.2 on 2026-01-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0037_alert_alertrecipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='md_message',
        ),
    ]
