# Generated by Django 5.0.2 on 2026-01-12 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0038_rename_message_alert_md_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlertRecipient',
            new_name='UserAlert',
        ),
        migrations.RenameIndex(
            model_name='useralert',
            new_name='discord_tra_user_id_ac5052_idx',
            old_name='discord_tra_user_id_7a503f_idx',
        ),
        migrations.RenameIndex(
            model_name='useralert',
            new_name='discord_tra_user_id_c76897_idx',
            old_name='discord_tra_user_id_53c70f_idx',
        ),
        migrations.RenameIndex(
            model_name='useralert',
            new_name='discord_tra_alert_i_1a169f_idx',
            old_name='discord_tra_alert_i_4894e2_idx',
        ),
    ]
