# Generated by Django 5.0.2 on 2026-01-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0039_rename_alertrecipient_useralert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordTrackerSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('weekly_invite_accesses', models.PositiveIntegerField(default=6, help_text='Maximum number of invite accesses allowed per user per week')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
