# Generated by Django 5.0.2 on 2026-01-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_tracker', '0040_discordtrackersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discordtrackersettings',
            name='id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False),
        ),
    ]
